"""Emit the appendix LaTeX tables straight from runs/, so they cannot drift.

    python paper/figures/make_appendix_tables.py > paper/appendix_tables.tex

Appendices do not count toward the 5-page limit, so these are free space and
they are where a sceptical reviewer looks for the per-category detail the main
text compresses.
"""

import collections
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
RUNS = os.path.join(ROOT, "runs")

MODELS = ["qwen-1.8b", "gemma-2b", "yi-6b", "qwen-7b", "qwen-14b"]


def esc(s):
    return s.replace("_", r"\_")


# ---------------------------------------------------------------- floors + n
floors, ns, hf = collections.defaultdict(dict), collections.defaultdict(dict), {}
for path in sorted(glob.glob(os.path.join(RUNS, "full_*", "report.json"))):
    d = json.load(open(path, encoding="utf-8"))
    m = d.get("model")
    hf[m] = (d.get("hf_id"), d.get("n_layers"), d.get("d_model"))
    for cat, v in (d.get("categories") or {}).items():
        fl = (v or {}).get("extraction_floor") or {}
        if "q05" in fl:
            floors[m][cat] = (fl["q05"], fl["median"], fl["min"], fl["n_items"])

cats = sorted({c for m in floors for c in floors[m]})
present = [m for m in MODELS if m in floors]

print("% ==== generated by paper/figures/make_appendix_tables.py - do not hand-edit ====")
print()

# ---------------------------------------------------------------- Table A1
print(r"\begin{table}[h]")
print(r"\centering")
print(r"\caption{Models. Exact Hugging Face identifiers as recorded in the run "
      r"manifests. Immutable revision SHAs were not captured at run time; we "
      r"record that as a reproducibility gap rather than reconstruct them.}")
print(r"\label{tab:models}")
print(r"\begin{tabular}{llrr}")
print(r"\toprule")
print(r"short name & Hugging Face id & layers & $d_{\mathrm{model}}$ \\")
print(r"\midrule")
for m in present:
    hid, L, dm = hf[m]
    print(rf"\texttt{{{esc(m)}}} & \texttt{{{esc(hid)}}} & {L} & {dm} \\")
print(r"\bottomrule")
print(r"\end{tabular}")
print(r"\end{table}")
print()

# ---------------------------------------------------------------- Table A2
print(r"\begin{table}[h]")
print(r"\centering")
print(r"\caption{Per-category split-half floor, all models. Each cell is "
      r"$q_{05}$ / median over 10 splits, with the number of items the direction "
      r"was fit on. Dashes are categories dropped by the behavioural task "
      r"control for that model.}")
print(r"\label{tab:floors-full}")
print(r"\small")
print(r"\begin{tabular}{l" + "r" * len(present) + "}")
print(r"\toprule")
print("category & " + " & ".join(rf"\texttt{{{esc(m)}}}" for m in present) + r" \\")
print(r"\midrule")
for c in cats:
    row = []
    for m in present:
        if c in floors[m]:
            q, med, _mn, n = floors[m][c]
            row.append(rf"{q:+.3f} / {med:+.3f} \tiny{{({n})}}")
        else:
            row.append("---")
    print(f"{esc(c)} & " + " & ".join(row) + r" \\")
print(r"\bottomrule")
print(r"\end{tabular}")
print(r"\end{table}")
print()

# ---------------------------------------------------------------- Table A3
ctrl = []
for path in sorted(glob.glob(os.path.join(RUNS, "*extraction*control*.json"))):
    d = json.load(open(path, encoding="utf-8"))
    for pair, v in d.get("pairs", {}).items():
        fl = v["floor"]
        ctrl.append((d.get("model"), pair, fl["n_items"], fl["q05"], fl["median"]))

print(r"\begin{table}[h]")
print(r"\centering")
print(r"\caption{Extraction positive control, all three models it was run on. A "
      r"topic-identity contrast through the identical capture site, estimator and "
      r"split-half procedure at matched $n$. It was not run on "
      r"\texttt{qwen-7b} or \texttt{qwen-14b}, which is a gap: those are the two "
      r"models carrying the clustering result.}")
print(r"\label{tab:control-full}")
print(r"\begin{tabular}{llrrr}")
print(r"\toprule")
print(r"model & topic contrast & $n$ & $q_{05}$ & median \\")
print(r"\midrule")
for m, pair, n, q, med in ctrl:
    a, b = pair.split(":")
    print(rf"\texttt{{{esc(m)}}} & {esc(a)} vs.\ {esc(b)} & {n} & {q:.3f} & {med:.3f} \\")
print(r"\bottomrule")
print(r"\end{tabular}")
print(r"\end{table}")
print()

qs = [c[3] for c in ctrl]
allq = [floors[m][c][0] for m in present for c in floors[m]]
print(rf"% control q05 range: {min(qs):.3f}-{max(qs):.3f} over {len(ctrl)} splits")
print(rf"% bias floor range : {min(allq):+.3f}-{max(allq):+.3f} over {len(allq)} cells")
print(rf"% cells clearing 0.50: {sum(1 for q in allq if q >= 0.5)}/{len(allq)}")
